# values.yaml for ELK Stack (Elasticsearch, Logstash, Kibana)

# -------------------------
# Elasticsearch Configuration
# -------------------------
elasticsearch:
  replicas: 1  # Single replica
  esConfig:
    elasticsearch.yml: |
      node.name: ${HOSTNAME}
      node.roles: ["master", "data", "ingest"]  # These roles are fine for a single-node cluster
      network.host: 0.0.0.0
      discovery.type: single-node  # Single-node cluster mode
      discovery.seed_hosts: ["elasticsearch-master"]
      http.port: 9200
  nodeGroup: "master"  # Single-node role
  antiAffinity: "soft"  # Avoid strict anti-affinity rules
  minimumMasterNodes: 1  # Prevent quorum issues in a single-node cluster
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"
  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 10Gi
  service:
    type: LoadBalancer  
    port: 9200
  security:
    enabled: true  # Set to true if you require security (username/password)
    elasticsearch:
      username: "elastic"  # If security is enabled, provide the username
      password: "changeme"  # Provide the password

