kibana:
# kibana_values.yaml

# Kibana replica settings (useful for high availability)
  replicas: 1


# Elasticsearch connection settings
  elasticsearchHosts: "http://elasticsearch-master:9200"   # Ensure this points to your Elasticsearch service

# Kibana service settings
  service:
    type: LoadBalancer   # Change to LoadBalancer if you want to expose Kibana externally
    port: 5601
    targetPort: 5601
    annotations: {}

# Resources for the Kibana pods (adjust these values based on your cluster's capacity)
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"

# Persistence settings (whether to persist data to volume)
  persistence:
    enabled: true  # Set to true if you want to persist Kibana data
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 8Gi

# Kibana ingress settings (to expose Kibana externally via HTTP/S)
  ingress:
    enabled: true   # Set to true if you want to expose Kibana via an ingress
    annotations: {}
    hosts:
      - host: kibana.local
        paths:
          - /
    tls: []  # Uncomment and configure if you need SSL/TLS

# Set Kibana's node selector, affinity, and tolerations for scheduling

# Extra Kibana configuration settings (if needed)
  kibanaConfig:
    server.name: "kibana"  # The name of the Kibana instance
    server.host: "0.0.0.0"  # Allow Kibana to be accessed from any host


# Enable/disable the Kibana dashboard
  dashboard:
    enabled: true  # Set to true if you want the default Kibana dashboard to be enabled

  security:
    enabled: true  # Set to true if you require security (username/password)
    elasticsearch:
      username: "elastic"  # If security is enabled, provide the username
      password: "changeme"  # Provide the password