logstash:
  replicas: 1  # Single instance for now, adjust as needed for high availability

  # Logstash input configuration (Beats)
  input:
    beats:
      enabled: true       # Enable Beats input plugin
      port: 5044          # Default Beats port for receiving logs

  # Logstash output configuration (Elasticsearch)
  output:
    elasticsearch:
      hosts: ["http://elasticsearch-master:9200"]  # Connect to Elasticsearch service (adjust host if needed)

  # Resource requests and limits
  resources:
    requests:
      memory: "1Gi"     # Memory request for Logstash pod
      cpu: "500m"       # CPU request for Logstash pod
    limits:
      memory: "2Gi"     # Memory limit for Logstash pod
      cpu: "1"          # CPU limit for Logstash pod

  # Logstash service configuration
  service:
    type: ClusterIP    # Internal-only access for service (change to LoadBalancer if you want external access)
    port: 5044         # The port that the service will expose for receiving Beats input
    targetPort: 5044   # Forward traffic to the same port inside the pod
    annotations: {}    # Optional service annotations (e.g., for monitoring or logging)

  # Elasticsearch output for Logstash (default)
  outputElastkicsearch:
    hosts: ["http://elasticsearch-master:9200"]  # Ensure this matches your Elasticsearch service URL

  # Persistent storage settings (if you want to persist data in Logstash)
  persistence:
    enabled: false  # Set to true if you want to persist Logstash data
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 8Gi

  elasticsearch:
     username: "elastic"  # If security is enabled, provide the username
     password: "changeme"  # Provide the password  

  # Logstash additional settings (optional)
  logstashPipeline:
  # Define Logstash pipeline directly here
    pipelineFile: |
      input {
        beats {
          port => 5044
        }
      }
      output {
        stdout {
          codec => rubydebug
        }
        elasticsearch {
          hosts => ["http://elasticsearch-master:9200"]
          index => "logstash-%{+YYYY.MM.dd}"
          user => "elastic"           
          password => "changeme"
        }
      }
