# loki_values.yaml

# Loki configuration
loki:
  # Configuration for Loki server


# Loki Replication & Resources
replicaCount: 1  # Number of Loki replicas in the deployment (set to 3 for HA)
resources:
  requests:
    memory: "2Gi"
    cpu: "1"
  limits:
    memory: "4Gi"
    cpu: "2"

# Persistence settings for Loki storage
persistence:
  enabled: true
  storageClassName: "standard"  # Specify the StorageClass (use default or your custom class)
  accessMode: ReadWriteOnce
  size: 50Gi  # Set the storage size for Loki data

# Loki Service Configuration
service:
  type: LoadBalancer  # Change to ClusterIP if you need an internal IP
  port: 3100

# Ingress Configuration (optional)
ingress:
  enabled: true  # Set to true if you want an ingress to expose Loki externally
  annotations: {}
  hosts:
    - host: loki.example.com
      paths:
        - /

# Loki's Index Configuration


# Loki's Security Configuration (Optional)
security:
  enabled: false  # Set to true to enable TLS or other security measures

# Loki UI Configuration (Optional)
ui:
  enabled: true  # Enable the UI for Loki
  service:
    port: 3101
