extends: existence
message: "Avoid using @site directive for referencing docs-specific partials and fragments. Use relative paths instead."
level: error
scope: raw
raw:
  - '@site/(?:vcluster|platform|.*versioned.*)/[_partials|_fragments]'
