extends: existence
message: "Code blocks must include language and title attribute: ```bash title=\"Description here\""
level: suggestion
scope: raw
nonword: true
tokens:
  - '(?m)^\s*```(?!.*title=").*\n[\s\S]*?\n\s*```$'