extends: existence
message: "Kubernetes/Platform API kinds like '%s' should not use backticks. Write them as plain text (e.g., StatefulSet not `StatefulSet`)."
level: warning
scope: raw
ignorecase: false
vocab: false
raw:
  # Use raw to have full control over the regex pattern
  - '`(?:StatefulSet|Deployment|DaemonSet|ReplicaSet|Job|CronJob|Pod|'
  - 'Service|Ingress|NetworkPolicy|Endpoints|EndpointSlice|'
  - 'ConfigMap|Secret|PersistentVolume|PersistentVolumeClaim|StorageClass|'
  - 'ServiceAccount|Role|ClusterRole|RoleBinding|ClusterRoleBinding|'
  - 'Namespace|Node|ResourceQuota|LimitRange|PodDisruptionBudget|'
  - 'HorizontalPodAutoscaler|VerticalPodAutoscaler|PodSecurityPolicy|'
  - 'CustomResourceDefinition|MutatingWebhookConfiguration|ValidatingWebhookConfiguration|'
  - 'VolumeSnapshot|VolumeSnapshotClass|VolumeSnapshotContent|'
  - 'CSIDriver|CSINode|VolumeAttachment|'
  - 'PriorityClass|RuntimeClass|PodTemplate|'
  - 'VirtualCluster|VirtualClusterInstance|VirtualClusterTemplate|'
  - 'SpaceInstance|SpaceTemplate|ProjectSecret|SharedSecret|'
  - 'DevPodWorkspace|DevPodWorkspaceInstance|DevPodWorkspaceTemplate|'
  - 'AppInstance|AppTemplate|ClusterRoleTemplate|AccessKey|'
  - 'VirtualClusterInstanceKubeConfig|VirtualService)`'