extends: existence
message: "Admonitions inside <Step> components must have zero indentation to avoid MDX parsing errors"
level: error
scope: raw
nonword: true
tokens:
  # This pattern specifically matches indented admonitions that appear within <Step> components
  # It captures the indented ::: line itself, which will position the error correctly
  - '(?ms)^(?=.*<Step[^>]*>)(?=.*</Step>)[ \t]+:::(note|tip|info|warning|danger|caution|important|success)\b'