extends: substitution
message: "'%s' should be 'vCluster Standalone' as a named feature in the vCluster portfolio."
level: warning
ignorecase: true
swap:
  '(?i)vcluster standalone': vCluster Standalone
  '(?i)vCluster standalone': vCluster Standalone
  '(?i)Vcluster Standalone': vCluster Standalone
