/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  siteSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {
      "type": "link",
      "label": "vCluster",
      "href": "/docs/vcluster",
      "className": "product-link"
    },
    {
      "type": "link",
      "label": "vCluster Platform",
      "href": "/docs/platform",
      "className": "product-link"
    }
  ],

};

export default sidebars;


