apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleepy-deployment
  labels:
    app: sleepy-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-dep-1
  template:
    metadata:
      labels:
        app: demo-dep-1
    spec:
      containers:
        - command:
            - /agnhost
            - serve-hostname
            - --http=true
            - --port=8080
          image: registry.k8s.io/e2e-test-images/agnhost:2.39
          name: sleepy-demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-sleep-deployment
  labels:
    sleep: no-thanks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-dep-2
  template:
    metadata:
      labels:
        app: demo-dep-2
    spec:
      containers:
        - command:
            - /agnhost
            - serve-hostname
            - --http=true
            - --port=8080
          image: registry.k8s.io/e2e-test-images/agnhost:2.39
          name: not-sleepy-demo
