---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcs-list-buckets
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcs-list-buckets
  template:
    metadata:
      labels:
        app: gcs-list-buckets
    spec:
      serviceAccountName: demo-sa
      containers:
      - image: google/cloud-sdk:slim
        command:
          - "gcloud"
          - "storage"
          - "buckets"
          - "list"
        name: gcs-pod
