genericSync:
  hooks:
    hostToVirtual:
    - apiVersion: v1
      kind: Node
      patches:
      - op: remove
        path: status.images
      - op: replace
        path: metadata.annotations
        value: {}
      - op: replace
        path: metadata.labels
        value: {}
      - fromPath: metadata.annotations["node.alpha.kubernetes.io/ttl"]
        op: copyFromObject
        path: metadata.annotations["node.alpha.kubernetes.io/ttl"]
      - fromPath: metadata.labels["kubernetes.io/arch"]
        op: copyFromObject
        path: metadata.labels["kubernetes.io/arch"]
      - fromPath: metadata.labels["kubernetes.io/hostname"]
        op: copyFromObject
        path: metadata.labels["kubernetes.io/hostname"]
      - fromPath: metadata.labels["kubernetes.io/os"]
        op: copyFromObject
        path: metadata.labels["kubernetes.io/os"]
      - fromPath: metadata.labels["beta.kubernetes.io/arch"]
        op: copyFromObject
        path: metadata.labels["beta.kubernetes.io/arch"]
      - fromPath: metadata.labels["beta.kubernetes.io/hostname"]
        op: copyFromObject
        path: metadata.labels["beta.kubernetes.io/hostname"]
      - fromPath: metadata.labels["beta.kubernetes.io/os"]
        op: copyFromObject
        path: metadata.labels["beta.kubernetes.io/os"]
      verbs: ["update", "patch", "create", "get", "list"]
    virtualToHost: []
