experimental:
  denyProxyRequests:
  - name: "Deny \"protected\" namespace"
    namespaces:
    - protected
    rules:
    - operations:
      - delete
      - update
      - patch
      apiGroups:
      - ''
      apiVersions:
      - "*"
      resources:
      - "namespaces/*"
      scope: Cluster
    - operations:
      - create
      - delete
      - update
      - patch
      apiGroups:
      - "*"
      apiVersions:
      - "*"
      resources:
      - "*"
      scope: Namespaced
    excludedUsers:
    - system:admin
    - system:serviceaccount:default:excluded

