#!/usr/bin/env bash
# Commit the label rewrites produced by check-eos-eol-labels.js --update and
# open (or force-update) the auto-sync pull request. Fixed branch name so
# successive runs don't pile up stale PRs.
#
# Required env:
#   GH_TOKEN  GitHub token with contents:write + pull-requests:write
#   SUMMARY   One-line description of the rewrites (from the script's output)

set -eo pipefail

branch="auto/sync-eos-eol-labels"
report_path="eos-eol-drift-report.md"

git config user.name "Loft Bot"
git config user.email "loft-bot@users.noreply.github.com"
git checkout -B "$branch"
git add docusaurus.config.js src/config/versionConfig.js
git commit -m "chore: sync EOS/EOL labels — ${SUMMARY}"
git push -u origin "$branch" --force

# If the branch already has an open PR, the force-push above is the update —
# don't try to create a second one.
if gh pr list --head "$branch" --state open --json number --jq '.[0].number' | grep -q .; then
  echo "Existing open PR on $branch updated by force-push; skipping pr create."
  exit 0
fi

report_md=""
if [ -f "$report_path" ]; then
  report_md=$(cat "$report_path")
fi

gh pr create \
  --base main \
  --head "$branch" \
  --title "chore: sync EOS/EOL labels (${SUMMARY})" \
  --body "$(cat <<EOF
Weekly auto-sync of EOS/EOL suffix labels in \`docusaurus.config.js\` and
\`src/config/versionConfig.js\` to match the dates published in
\`docs/_partials/vcluster_supported_versions.mdx\` and
\`docs/_partials/platform_supported_versions.mdx\`.

## Changes

${SUMMARY}

${report_md}

## Guardrails

- Only suffix transitions are applied (\`(EOS)\` → \`(EOL)\`; bare or \`Stable\` → \`(EOS)\`/\`(EOL)\`).
- A version is **not** moved between \`docusaurus.config.js\` (active) and \`src/config/versionConfig.js\` (archived) by this automation. Run the archive workflow described in \`.claude/skills/vcluster-docs-archiver\` when a version should be fully retired.
- If a label loses its \`Stable\` suffix here, add \`Stable\` to the new latest version in \`docusaurus.config.js\` before merging.

Generated by [\`.github/workflows/check-eos-eol-labels.yml\`](.github/workflows/check-eos-eol-labels.yml).
EOF
)"
