sync:
  toHost:
    # we want to rewrite ingress cert-manager.io/issuer annotations
    ingresses:
      enabled: true
      patches:
        - path: metadata.annotations["cert-manager.io/issuer"]
          reference:
            apiVersion: cert-manager.io/v1
            kind: Issuer

    customResources:
      # sync certificates
      certificates.cert-manager.io:
        enabled: true
        patches:
          - path: spec.secretName
            reference:
              apiVersion: v1
              kind: Secret
          - path: spec.issuerRef
            reference:
              apiVersion: cert-manager.io/v1
              kind: Issuer   # defaults to Issuer
              kindPath: kind # to also allow ClusterIssuer
              namePath: name
          - path: status.nextPrivateKeySecretName
            reference:
              apiVersion: v1
              kind: Secret
      # sync issuers
      issuers.cert-manager.io:
        enabled: true
        patches:
          - path: spec.acme.privateKeySecretRef.name
            reference:
              apiVersion: v1
              kind: Secret

  fromHost:
    customResources:
      # sync cluster issuers in read-only mode
      clusterissuers.cert-manager.io:
        enabled: true
        scope: Cluster