# American Spelling Enforcement (Swap Mapping)
# Adapted from the GitLab ruleset (reversed for American spelling)
extends: substitution
message: "Use the US spelling '%s' instead of the British '%s'."
link: 'https://developers.google.com/style/spelling'
ignorecase: true
level: warning
swap:
  aeon: eon
  aeroplane: airplane
  ageing: aging
  aluminium: aluminum
  anaemia: anemia
  anaesthesia: anesthesia
  analyse: analyze
  annexe: annex
  apologise: apologize
  authorisation: authorization
  authorised: authorized
  authorising: authorizing
  authorise: authorize
  behaviour: behavior
  busses: buses
  calibre: caliber
  capitalised: capitalized
  categorise: categorize
  categorised: categorized
  categorises: categorizes
  categorising: categorizing
  centre: center
  cheque: check
  civilisation: civilization
  civilise: civilize
  colour: color
  cosy: cozy
  cypher: cipher
  dependant: dependent
  defence: defense
  distil: distill
  draught: draft
  encyclopaedia: encyclopedia
  enquiry: inquiry
  enrol: enroll
  enrolment: enrollment
  enthral: enthrall
  favourite: favorite
  fibre: fiber
  fillet: filet
  flavour: flavor
  furore: furor
  fulfil: fulfill
  gaol: jail
  grey: gray
  humour: humor
  honour: honor
  initialled: initialed
  initialling: initialing
  instil: instill
  jewellery: jewelry
  labelling: labeling
  labelled: labeled
  labour: labor
  libellous: libelous
  licence: license
  likeable: likable
  liveable: livable
  lustre: luster
  manoeuvre: maneuver
  marvellous: marvelous
  matt: matte
  meagre: meager
  metre: meter
  modelling: modeling
  modernised: modernized
  modernisation: modernization
  minimise: minimize
  minimised: minimized
  minimisation: minimization
  moustache: mustache
  neighbour: neighbor
  normalise: normalize
  offence: offense
  organise: organize
  organised: organized
  orientated: oriented
  paralyse: paralyze
  prioritised: prioritized
  prioritisation: prioritization
  plough: plow
  pretence: pretense
  programme: program
  publicised: publicized
  publicisation: publicization
  pyjamas: pajamas
  rateable: ratable
  realise: realize
  realised: realized
  realisation: realization
  recognise: recognize
  reconnoitre: reconnoiter
  rumour: rumor
  sabre: saber
  saleable: salable
  saltpetre: saltpeter
  sceptic: skeptic
  sepulchre: sepulcher
  signalling: signaling
  sizeable: sizable
  skilful: skillful
  sombre: somber
  smoulder: smolder
  speciality: specialty
  spectre: specter
  splendour: splendor
  standardise: standardize
  standardised: standardized
  sulphur: sulfur
  synthesised: synthesized
  synthesisation: synthesization
  theatre: theater
  travelled: traveled
  traveller: traveler
  travelling: traveling
  unshakeable: unshakeable
  utilised: utilized
  wilful: willful
  yoghurt: yogurt
  summarised: summarized
  summarisation: summarization