extends: capitalization
message: "'%s' should use sentence-style capitalization."
link: "https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings"
level: warning
scope: heading
match: $sentence
indicators:
  - ":"
  - "-"
exceptions:
  - ACM
  - ALB
  - Argo CD
  - Amazon
  - AWS
  - Certificate Manager
  - CSI
  - EBS
  - HTTPS
  - Ingress
  - Kine
  - RDS
  - Route 53
  - Verify
  - VPC
  - Azure
  - API Server
  - Authorization
  - BareMetalHost
  - BareMetalHosts
  - BMC
  - CIS Hardening
  - CLI
  - Cosmos
  - DHCP
  - Docker
  - DNS
  - Emmet
  - gRPC
  - I
  - Kubernetes
  - Linux
  - macOS
  - Marketplace
  - MetalLB
  - MongoDB
  - OSImage
  - PXE
  - REPL
  - SSH
  - SSHKey
  - Studio
  - TypeScript
  - URLs
  - Visual
  - VS
  - Windows
  - JSON
  - vCluster
  - vMetal
  - vNode
  - \bPro\b
  - OpenCost
  - Helm
  - FIPS