extends: existence
message: "In general, use American spelling instead of '%s'."
link: 'https://developers.google.com/style/spelling'
ignorecase: true
level: warning
tokens:
  - '(?:\w+)nised?'
  - 'colour'
  - 'labour'
  - 'centre'
  - 'favourite'
  - 'behaviour'
  - 'organise'
  - 'realise'
  - 'defence'
  - 'offence'
  - 'analyse'
  - 'apologise'
  - 'programme'
  - 'travelling'
  - 'labelling'
  - 'jewellery'
  - 'sulphur'
  - 'cancelling'
