name: Auto-approve bot PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-approve:
    uses: loft-sh/github-actions/.github/workflows/auto-approve-bot-prs.yaml@main
    with:
      auto-merge: false
      trusted-authors: 'renovate[bot],loft-bot,github-actions[bot],dependabot[bot]'
      app-id: ${{ secrets.AUTO_APPROVE_APP_ID }}
    secrets:
      app-private-key: ${{ secrets.AUTO_APPROVE_APP_PRIVATE_KEY }}
      gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}
