name: Backport Documentation

on:
  pull_request:
    types: [closed, labeled]
    paths:
      - 'vcluster/**'
      - 'platform/**'

jobs:
  backport:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true ||
        (github.event.action == 'labeled' && startsWith(github.event.label.name, 'backport-v'))
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Commit hash for testing
      - name: Backport Docusaurus Changes
        uses: loft-sh/docs-backport-action@877d906
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}