name: Backport Documentation

on:
  pull_request_target:
    types: ["labeled", "closed"]
    paths:
      - 'vcluster/**'
      - 'platform/**'

jobs:
  backport:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true ||
        (github.event.action == 'labeled' && startsWith(github.event.label.name, 'backport-v'))
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0

      - name: Backport Docusaurus Changes
        uses: loft-sh/docs-backport-action@a56a443f5ad542602526ac06f3804d24e3cd010b # v1.3.2
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
