name: cli-docs

on:
  # WIP just to test without bugging people with PRs
  pull_request:
    types: [reopened, converted_to_draft]

  repository_dispatch:
    types: [ update-cli-docs ]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout vcluster repository
        uses: actions/checkout@v4
        with:
          repository: loft-sh/vcluster
          fetch-depth: 0
          ref: ${{ github.event.client_payload.ref }}
          path: vcluster-repo
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Setup Just
        uses: extractions/setup-just@v2
      - name: Generate cli docs
        working-directory: vcluster-repo
        run: |
          pwd
          ls
          ls ./vcluster-repo
      - name: Copy generated files
        env:
          PR_TITLE: ${{ github.event.client_payload.title || 'No title' }}
          PR_REF: ${{ github.event.client_payload.ref || 'main' }}
          PR_VERSION: ${{ github.event.client_payload.version || 'wip-version' }}
        run: |
          # set git info
          git config --global user.name "Loft Bot"
          git config --global user.email 'loft-bot@users.noreply.github.com'
          pwd
          ls
          cp -r ./vcluster-repo/vcluster/docs/pages/cli vcluster-docs/vcluster

          git checkout -b "CLI-DOC-$PR_REF"
          git add ./vcluster/cli

          # if there are no changes, exit early
          if git diff-index --quiet HEAD --; then
            exit 0
          fi

          git commit -m "DOC Update from {{ github.event.client_payload.title }}"
          git push origin "CLI-DOC-$PR_REF"
          gh pr create --base main -t "DOC Update from {{ github.event.client_payload.title }}" --body "Autogenerated PR for CLI docs"

