name: Update CLI Docs

on:
  repository_dispatch:
    types: [ update-cli-docs ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout vcluster repository
        uses: actions/checkout@v4
        with:
          repository: loft-sh/vcluster
          fetch-depth: 0
          ref: ${{ github.event.client_payload.ref }}
      - run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Setup Just
        uses: extractions/setup-just@v2
      - name: Generate cli docs
        working-directory: ./vcluster
        run: |
          just generate-cli-docs
      - name: Copy generated files
        working-directory: ./vcluster-docs
        run: |
          cp -r ../vcluster/docs/pages/cli ./vcluster
          git add ./vcluster/cli
          git commit -m "DOC Update from {{ github.event.client_payload.title }}"
          gh pr create --base main -t "DOC Update from {{ github.event.client_payload.title }}" --repo loft-sh/vcluster-docs --body "Autogenerated PR for CLI docs"

