name: Create follow up linear issue

on:
  pull_request_target:
    types:
      - labeled
jobs:
  create-linear-issue-on-pull-request:
    if: ${{ github.event.label.name == 'follow-up' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create the Linear Issue
        id: createIssue
        uses: ctriolo/action-create-linear-issue@v0.7
        with:
          linear-api-key: ${{secrets.LINEAR_API_KEY}}
          linear-team-key: "DOC"
          linear-issue-title: ${{github.event.pull_request.title}}
          linear-issue-description: ${{github.event.pull_request.body}}
          linear-attachment-url: ${{github.event.pull_request.html_url}}
          linear-attachment-title: ${{github.event.pull_request.title}}

      - name: Create comment in PR with Linear Issue link
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.createIssue.outputs.linear-issue-url }}"


