name: Linear PR Comments

on:
  pull_request:
    types: [opened, edited]
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  add-linear-links:
    name: Add Linear Issue Links
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Linear PR Commenter
        uses: loft-sh/github-actions/.github/actions/linear-pr-commenter@linear-pr-commenter/v1
        with:
          pr-number: ${{ github.event.pull_request.number }}
          repo-owner: ${{ github.repository_owner }}
          repo-name: ${{ github.event.repository.name }}
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          linear-token: ${{ secrets.LINEAR_API_KEY }}
        timeout-minutes: 3
