name: Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - "platform/**/*.mdx" # Include .mdx files in platform folder and subfolders
      - "platform/**/*.md" # Include .md files in platform folder and subfolders
      - .github/workflows/reviewdog.yaml
      - "*.md"

jobs:
  markdownlint:
    name: runner / markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run Misspell with Reviewdog
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          reporter: github-pr-review

  vale:
    name: runner / vale platform
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: "platform/**/*.mdx"
      - name: Install venv for vale on ubuntu latest
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          venv="$HOME/.local/share/venv"
          python3 -m venv "$venv"
          echo "$venv/bin" >> $GITHUB_PATH
      - name: Run Vale with Reviewdog
        uses: errata-ai/vale-action@reviewdog
        if: steps.changed-files.outputs.all_changed_files != ''
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          fail_on_error: true
          reporter: github-pr-review
          version: 3.7.1
          files: ${{ steps.changed-files.outputs.all_changed_files }}
          separator: " "
