name: Sync Next Branch

# This workflow keeps the next branch in sync with main:
# - Tries to rebase next onto main
# - If rebase is clean → automatically pushes to next
# - If there are conflicts → creates a PR for manual resolution

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Configure git
        run: |
          git config --global url."https://loft-bot:${{ secrets.GH_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"
          git config --global user.name "Loft Bot"
          git config --global user.email "loft-bot@users.noreply.github.com"

      - name: Sync branches
        run: |
          ./hack/sync-branches.sh > sync-output.txt 2>&1
          cat sync-output.txt

          if grep -q "Clean rebase successful" sync-output.txt; then
            git push --force-with-lease origin HEAD:next
            echo "Successfully rebased next onto main"

          elif grep -q "Conflicts detected" sync-output.txt; then
            BRANCH_NAME=$(grep "created branch:" sync-output.txt | cut -d: -f2 | tr -d ' ')
            git push origin "$BRANCH_NAME"

            gh pr create \
              --title "Sync: Merge main into next (rebase conflicts)" \
              --body "Automated sync from main to next branch.

              Rebase conflicts detected - falling back to merge strategy for manual resolution.
              
              This PR contains a merge commit because rebasing had conflicts that need manual resolution.
              After resolving, consider rebasing the next branch to maintain clean history." \
              --base next \
              --head "$BRANCH_NAME" \
              --label "sync"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}