name: Sync Next Branch

# This workflow keeps the next branch in sync with main:
# - Tries to rebase next onto main
# - Verifies no commits are lost before pushing
# - If rebase is clean → automatically pushes to next
# - If there are conflicts → creates a PR for manual resolution

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Configure git
        run: |
          git config --global url."https://loft-bot:${{ secrets.GH_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"
          git config --global user.name "Loft Bot"
          git config --global user.email "loft-bot@users.noreply.github.com"

      - name: Sync branches
        run: |
          ./hack/sync-branches.sh > sync-output.txt 2>&1 || SYNC_EXIT_CODE=$?
          cat sync-output.txt
          
          # Check exit code first - script exits 1 if commit loss detected
          if [ "${SYNC_EXIT_CODE:-0}" -eq 1 ]; then
            echo "::error::Sync failed - possible commit loss detected!"
            exit 1
          fi
          
          if grep -q "Clean rebase successful" sync-output.txt; then
            git push --force-with-lease origin HEAD:next
            echo "::notice::Successfully rebased next onto main"
            
          elif grep -q "No new commits from main" sync-output.txt; then
            echo "::notice::Next branch is already up to date"
            exit 0
            
          elif grep -q "Conflicts detected" sync-output.txt; then
            BRANCH_NAME=$(grep "created branch:" sync-output.txt | cut -d: -f2 | tr -d ' ')
            git push origin "$BRANCH_NAME"
            
            # Create PR
            gh pr create \
              --title "Sync: Merge main into next (rebase conflicts)" \
              --body "Automated sync from main to next branch. Rebase had conflicts - using merge strategy to preserve all commits. Please resolve conflicts and merge." \
              --base next \
              --head "$BRANCH_NAME" \
              --label "sync"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}