name: Validate content with Vale

on:
  pull_request:
    paths:
      - 'platform/**/*.mdx'  # Include .mdx files in platform folder and subfolders
      - 'platform/**/*.md'   # Include .md files in platform folder and subfolders

  workflow_dispatch:

jobs:
  lint-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: 'platform/**/*.mdx'

      - name: Install Vale
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          wget https://github.com/errata-ai/vale/releases/download/v3.7.1/vale_3.7.1_Linux_64-bit.tar.gz
          tar -xzf vale_3.7.1_Linux_64-bit.tar.gz
          sudo mv vale /usr/local/bin/vale
          sudo chmod +x /usr/local/bin/vale

      - name: Run Vale
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          if [ -n "${{ steps.changed-files.outputs.all_changed_files }}" ]; then
            vale --config=".vale.ini" ${{ steps.changed-files.outputs.all_changed_files }} | tee /dev/stderr | wc -l | { read wc; test $wc -eq 1; }
          else
            echo "No changed files to lint."
          fi