name: Validate Glossary Terms

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.mdx'
      - 'src/data/glossary.yaml'
      - 'src/components/GlossaryTerm/**'
      - 'scripts/validate-glossary-terms.js'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  validate-glossary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Validate glossary terms
        run: npm run validate-glossary